# Generated by Django 5.0.4 on 2024-04-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_options_member_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(choices=[('active', 'true'), ('unactive', 'false')], default=True),
        ),
    ]
