# Generated by Django 5.0.4 on 2024-04-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_client_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
