# Generated by Django 5.0.4 on 2024-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_update_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, default='noimag.png', null=True, upload_to='project'),
        ),
    ]
